# Generated by Django 4.2.16 on 2025-10-10 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailmedia', '0004_duration_optional_floatfield'),
        ('blog', '0028_blogdetailpage_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetailpage',
            name='video',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'video'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailmedia.media'),
        ),
    ]
